FROM python:3.10-slim-buster

WORKDIR /root
ENV VENV /opt/venv
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV PYTHONPATH /root

RUN apt-get update && apt-get install build-essential git -y

COPY requirements_slack.txt /root/requirements.txt
WORKDIR /root

RUN pip install -r /root/requirements.txt

COPY flyte-slack-data /root/flyte-slack-data
