FROM pytorch/pytorch:2.0.0-cuda11.7-cudnn8-devel

WORKDIR /root
ENV VENV /opt/venv
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV PYTHONPATH /root

RUN apt-get update && apt-get install build-essential git -y

COPY requirements_slack.txt /root/requirements_slack.txt
RUN pip install -r /root/requirements_slack.txt

ADD flyte-slack-data /root/flyte-slack-data
